/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.junit.Test;

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;

public class AppTest {
    @Test
    public void testRemovePunctuation() {
        assertThat(App.removePunctuation("Hello, this is a test!!"), is("Hellothisisatest"));
    }

    @Test
    public void testCipherPositiveShiftLowercase() {
        assertThat(App.cipher("abcxyz", 3), is("defabc"));
    }

    @Test
    public void testCipherPositiveShiftUppercase() {
        assertThat(App.cipher("ABCXYZ", 3), is("DEFABC"));
    }

    @Test
    public void testCipherNegativeShiftLowercase() {
        assertThat(App.cipher("defabc", -3), is("abcxyz"));
    }

    @Test
    public void testCipherNegativeShiftUppercase() {
        assertThat(App.cipher("DEFABC", -3), is("ABCXYZ"));
    }

    @Test
    public void testFormatBlocksNoPadding() {
        assertThat(App.formatBlocks("abcdefghij", 5), is("ABCDE FGHIJ"));
    }

    @Test
    public void testFormatBlocksWithPadding() {
        assertThat(App.formatBlocks("abcdefghijkl", 5), is("ABCDE FGHIJ KLXXX"));
    }

    @Test
    public void integrationTest() {
        String input = "Hello, this is a test!";

        String filteredText = App.removePunctuation(input);
        String cipheredText = App.cipher(filteredText, 3);
        String output = App.formatBlocks(cipheredText, 5);

        assertThat(output, is("KHOOR WKLVL VDWHV WXXXX"));
    }
}
